### PR TITLE
Mouse actions: Start copying on drag and paste on wheel click.

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by kruton** [comment]
Does this break the swipe to next screen stuff? This is a better use of primary click at any rate.

Maybe we can have mouse pointers hovering on the right or left edge of the screen flip to the next terminal?

**Comment by jklein24** [comment]
Hmm I suppose this breaks the swipe between screens when using a mouse, but it still works with your finger. I find swipe a bit awkward for this purpose with a mouse anyway, particularly on large screens. I don't think it's too big of a deal. There's also a pending request from @bengolds to add tabs on large screens anyway.

**Comment by jklein24** [comment]
uh oh, my git history went nuts... fixing it.

**Comment by jklein24** [comment]
Fixed.

**Comment by jklein24** [comment]
Strange stuff going on here... it seems like connectbot:master is missing all the merged commits from my previous PRs somehow. Can you take a look at what happened on master?

**Comment by kruton** [comment]
Looks like my bad. I merged in 41a1eb43266d64c3fe8f519ed00d16f6436d1cae again to fix the history.

**Comment by jklein24** [comment]
OK, I'm fairly convinced everything is sane now.

**Pull request merged**
