### PR TITLE
Add FAB to port forward activity.

### PR DESCRIPTION
**Pull request by khorimoto**

### CODE REVIEW

**Comment by jklein24** [comment]
Looks like you have some unused imports, but otherwise LGTM

**Comment by khorimoto** [comment]
> Looks like you have some unused imports, but otherwise LGTM

Fixed.

**Comment by khorimoto** [comment]
More lint errors fixed.

**Comment by wp9015362** [comment]
@khorimoto & @jklein24 :

May I ask how one can access the port forward activity?

Tapping and holding on a host in the host list offers "Edit port forwards", but it's grayed out and can not be selected.

How do you access the port forward activity?

Regards

**Comment by khorimoto** [comment]
@wp9015362: It depends on the connection types. SSH, for example, allows port forwarding, but local, for example, does not.

**Pull request merged**
