### PR TITLE
Change virtual keyboard by semi-transparent buttons and add arrow keys.

### PR DESCRIPTION
**Pull request by alescdb**
Changed ImageView by Button except for button_keyboard in ConsoleActivity and add Up, Down, Left, Right arrow keys.

screenshot_2015-08-07-15-52-13

### CODE REVIEW

**Comment by kruton** [comment]
Thanks. @jklein24 looks like you won't have to do this.

**Comment by adb2001** [comment]
I've made UI improvements and remove hardcoded text.
It looks good on my N5 and N9 in landscape and portrait.

screenshot_2015-08-07-18-55-26

**Comment by jklein24** [comment]
nice :-)

**Comment by kruton** [comment]
Merged with commit a4c53008744a2b04f6b38469bc75d713b713ed68.

**Pull request closed without merging**
