### PR TITLE
Change menu copy and paste icons and add them to action menu (if room)

### PR DESCRIPTION
**Pull request by alescdb**
sans titre

### CODE REVIEW

**Comment by alescdb** [comment]
Travis CI build failed because lint issues increased, but I think declaring the whole member onCreateOptionsMenu() as @TargetApi(11) is more dangerous than letting lint warn us (since we can't use the @TargetApi annotation inside methods cf. https://code.google.com/p/android/issues/detail?id=27511).

Any advise ?

> ConsoleActivity.java:715: Field requires API level 11 (current min is 8): android.view.MenuItem#SHOW_AS_ACTION_IF_ROOM
> 714 		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB)
> 715 			copy.setShowAsAction(MenuItem.SHOW_AS_ACTION_IF_ROOM);

**Comment by kruton** [comment]
You can just extract that part out to another method and mark that method.

**Comment by kruton** [comment]
Also I put in the IntelliJ formatting that should match what we have currently. Is that not working for you?

**Comment by alescdb** [comment]
IntelliJ formatting seems to be OK for me now. But "Use Tab character" is still unchecked in my codestyle settings (whatever I choose : "Project" settings or "Default" settings).

**Comment by kruton** [comment]
@bengolds what say you?

**Comment by bengolds** [comment]
Can we use the default material design copy/paste icons?
https://www.google.com/design/icons/
"content copy" and "content paste"

**Comment by alescdb** [comment]
This is what I used in my last commit, screenshot is not up to date, sorry for that.

**Comment by alescdb** [comment]
Up to date screenshot.

sans titre

**Comment by alescdb** [comment]
Oops, I don't know why I push to the wrong branch :-/

**Comment by alescdb** [comment]
@kruton I've tried everything, resetting Android Studio settings to default, using Project Codestyle, and I still can't match the ConnectBot sources codestyle (Java & XML).
I'm using Android Studio 1.4 AI-141-2180789 (Canary Channel). The file ".idea/codeStyleSettings.xml" seems to have no effect whatsoever.
Can you please "Export Settings.../Code Style" so I can import them as my default settings ?

**Comment by kruton** [comment]
I'll try to come up with a better `app.iml` generation scheme instead of checking it in.

**Pull request merged**
