### PR TITLE
Reset autohide timer when an arrow button is clicked to allow multiple click

### PR DESCRIPTION
**Pull request by alescdb**
- Reset auto hide timer when an arrow button is clicked to allow multiple arrow click.
- Create onEmulatedKeyClicked() via a global OnClickListener (emulatedKeysListener) handling all button events (except keyboard) since they all share the same code, we could also implement OnClickListener directly in ConsoleActivity to avoid the use of a global variable.
- Remove unused keyboard png (esc, tab, ctrl)
- Add haptic feedback to all keys except tab and keyboard.

PS: This time the patch looks good.

### CODE REVIEW

**Comment by kruton** [comment]
Any reason why the tab doesn't vibrate? Are you trying to match existing behavior?

**Comment by alescdb** [comment]
The main reason is that Tab always produce a visible result, and when it does not (eg in "bash" for auto completion when there is more than one match) it produce a bell.

That was the idea, now if you prefer I can remove the Tab exception :)

**Comment by kruton** [comment]
Yeah, let's remove that because the delay might be so great on the SSH link over mobile networks. Otherwise this looks great. Thanks.

**Comment by alescdb** [comment]
Good point, Changes done.

**Pull request merged**
