### PR TITLE
Better lint output for Travis-CI

### PR DESCRIPTION
**Pull request by kruton**
This uses xqilla to run a better XPath 2.0 query that outputs a terse
one-line description of the problem which is easier to diff in Travis-CI
build output.

### CODE REVIEW

**Comment by jklein24** [comment]
Nice!

**Comment by khorimoto** [comment]
YES!!!!!

**Comment by kruton** [comment]
This won't work until travis-ci/apt-package-whitelist#1518 is in the running Travis-CI workers.

**Comment by rhansby** [comment]
:+1:

**Pull request merged**
