### PR TITLE
Add a tab button to the emulated keys above the soft keyboard.

### LINKED ISSUE #92: Add a tab button where ctrl and esc are
The default android virtual keyboard has no tab button, so this would be convenient.

### PR DESCRIPTION
**Pull request by jklein24**
Fixes #92

### CODE REVIEW

**Comment by jklein24** [comment]
@kruton let me know if there's anything I should do wrt compression on the png or translations for the new string.

**Comment by kruton** [comment]
Could you attach a screenshot of what it looks like after this change?

**Comment by kruton** [comment]
Also I have a project that uses gimp to automatically create assets based on a scheme program. It might be worth converting the soft buttons to this or making them into TextView instead.

Take a look at https://github.com/connectbot/assets

**Comment by jklein24** [comment]
tab_button


I'll check out the asset creator too.

**Comment by jklein24** [comment]
tab_button

**Comment by jklein24** [comment]
fwiw, +1 to making these buttons into actual text buttons.

**Pull request merged**
