### PR TITLE
Add tabs when there's more than one terminal active.

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by jklein24** [comment]
A couple notes here:

1) Let me know if I'm missing something with themes here that could make this change simpler. It took me a while to track down various missing styles and make the tabs actually render.

2) Right now the tabs show up on all devices, but I was considering making them layout-large only. Here's a screenshot on the N5. I actually think it looks pretty good, but I'm happy to make it large screens only if you want.

device-2015-08-10-103705

**Comment by alescdb** [comment]
And I found a FC while trying :
  - Open a connection that ask for a password,
  - Enter bad passwords as long as ConnectBot ask for it,
  - When ConnectBot detect connection reset and ask to close say "Yes"
  - FC

E/AndroidRuntime(31567): java.lang.IllegalStateException: The application's PagerAdapter changed the adapter's contents without calling PagerAdapter#notifyDataSetChanged! Expected adapter item count: 2, found: 1 Pager id: org.connectbot.debug:id/console_flip Pager class: class android.support.v4.view.ViewPager Problematic adapter: class org.connectbot.ConsoleActivity$TerminalPagerAdapter
E/AndroidRuntime(31567): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:999)
E/AndroidRuntime(31567): 	at android.support.v4.view.ViewPager.populate(ViewPager.java:951)
E/AndroidRuntime(31567): 	at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1473)
E/AndroidRuntime(31567): 	at android.view.View.layout(View.java:15658)
E/AndroidRuntime(31567): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(31567): 	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1076)
E/AndroidRuntime(31567): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(31567): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(31567): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(31567): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(31567): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(31567): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(31567): 	at com.android.internal.widget.ActionBarOverlayLayout.onLayout(ActionBarOverlayLayout.java:494)
E/AndroidRuntime(31567): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(31567): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(31567): 	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:579)
E/AndroidRuntime(31567): 	at android.widget.FrameLayout.onLayout(FrameLayout.java:514)
E/AndroidRuntime(31567): 	at android.view.View.layout(View.java:15671)
E/AndroidRuntime(31567): 	at android.view.ViewGroup.layout(ViewGroup.java:5038)
E/AndroidRuntime(31567): 	at android.view.ViewRootImpl.performLayout(ViewRootImpl.java:2086)
E/AndroidRuntime(31567): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1843)
E/AndroidRuntime(31567): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
E/AndroidRuntime(31567): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
E/AndroidRuntime(31567): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
E/AndroidRuntime(31567): 	at android.view.Choreographer.doCallbacks(Choreographer.java:580)
E/AndroidRuntime(31567): 	at android.view.Choreographer.doFrame(Choreographer.java:550)
E/AndroidRuntime(31567): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
E/AndroidRuntime(31567): 	at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime(31567): 	at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime(31567): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime(31567): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime(31567): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(31567): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime(31567): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime(31567): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by jklein24** [comment]
Thanks, @alescdb. Are you able to repro that without this PR on master? It seems more likely that this would have been caused from one of my other recent changes.

**Comment by alescdb** [comment]
No I can't reproduce on master.

OK, I found the exact actions to reproduce :
- Open a first connection,
- Open a second connection,
- Return to the first connection by swipping (not with Tabs)
- Exit (with command line exit), ConnectBot ask "Close Yes/No", say "Yes"
- FC

**Comment by jklein24** [comment]
Weird... I can't seem to repro with your steps here. I'll keep messing around and trying to break it.

**Comment by alescdb** [comment]
If it can help I made a video, I can reproduce 100% (only swipe cause FC not clicking on the tab) :
http://youtu.be/WwkuQs-E6SY

**Comment by jklein24** [comment]
Thanks! Can you try again now? I think I've tracked it down and fixed it, but you seem to have a more reliable repro environment for some reason.

**Comment by alescdb** [comment]
Same behaviour with commit 56f4def53bfe7bf1886a525c9a7cd67324091a51

**Comment by kruton** [comment]
Are you sure tabs are what you want here? We had another branch where someone had converted everything to Fragments where we could have the host list on the left and switch between them there.

At any rate, I think this needs to be made big screen only. The action bar already takes up too much room on the phone.

**Comment by jklein24** [comment]
@kruton: Yeah, I think tabs are the nicer solution from a UX perspective than a drawer panel. I'll work on making this large screen only.

@alescdb: Even exactly following your repro steps from the video and in your comments, I'm totally unable to repro for some reason on my Nexus 5 or Nexus 9. What device and Android version are you on? @kruton, are you able to repro this?

**Comment by jklein24** [comment]
Ah, now I have it happening at least enough to get some breakpoints in and see what's going on. I'll keep digging.

**Comment by alescdb** [comment]
@jklein24 I have a Nexus 5 and a Nexus 9, both on the latest 5.1.1

Just some ideas for small devices : 
- A dropdown in ActionBar,
- Navigation Tabs in ActionBar,
- PagerTitleStrip (which is smaller than tabs and can have a lot of items)

**Comment by jklein24** [comment]
cc @bengolds for UX input on small screens

**Comment by jklein24** [comment]
Status of the crash:

I believe this is a threading issue because the bridges array (owned by the TerminalManager) is the backing data source of the adapter. When a bridge is disconnected, TerminalManager removes the bridge from the bridges array and then sends a message to ConsoleActivity, which calls notifyDataSetChanged. From my added logs, it looks like when the crash occurs, it happens after the message is sent by TerminalManager, but before it's received by ConsoleActivity. If there's a layout right at that point, things explode.

Maybe if there's a disconnectHandler, we should assume it will also handle the removal from the bridges array so that it can be done on the UI thread. That seems like pretty nasty encapsulation breaking, though. I'm still pretty new to Android development so the concept of which pieces need to be on the UI thread and how to coordinate that is all a bit foreign to me. Is there a common pattern that I'm missing here?

**Comment by jklein24** [comment]
OK, now I think I got it for real! @alescdb, please tell me you can't repro still :-). Also if either of you knows a better way to solve this issue in TerminalBridge, let me know. As I mentioned, I'm new to the best-practices for multi-threading on Android.

**Comment by alescdb** [comment]
@jklein24 I confirm that commit b067b78b004f8dd2607fe1acea0e7ec47e108212 (with tabs) and 64f59c9c98b7b827f1475e8e98cb3929ba0c4d93 (without tabs on my N5) are both OK, no more FC !

**Pull request merged**
