### PR TITLE
Remove unused add host dialog from HostListActivity.

### PR DESCRIPTION
**Pull request by jklein24**

### CODE REVIEW

**Comment by jklein24** [comment]
sigh... @kruton any idea what's up with the linter here? I just removed some code...

**Comment by alescdb** [comment]
I'm not kruton but I guess it's dia_add_host (unused)

**Comment by alescdb** [comment]
In fact all the warning starting with a '+' so :
R.string.button_add (and all translations)
R.string.button_cancel (and all translations)
...

**Comment by kruton** [comment]
Yes, there's just a lot more you can remove since you removed all the
references to them :)

**Pull request merged**
