### PR TITLE
Fix missing summaries for SwitchPreferences in host editing list.

### LINKED ISSUE #222: Summaries missing for SwitchPreferences in host editing list
See below screenshots.

Bad in API23
edithost23

Good in API10
edithost10

### PR DESCRIPTION
**Pull request by rhansby**
Fixes #222

### CODE REVIEW

**Comment by jklein24** [comment]
Mind rebasing to merge your two commits into one? Hoping to keep the history clean.

**Comment by rhansby** [comment]
Sure. I'll delete this branch and resubmit

**Comment by rhansby** [comment]
@jklein24 Are you sure you want me to squash these two commits together? 04df1f8 will get lost in the huge 6d0bad1

**Comment by jklein24** [comment]
Resolved offline and git history magically clean :-). Will merge as soon as the tests are happy.

**Pull request merged**
