### PR TITLE
Add Material theme palette

### LINKED ISSUE #167: ConnectBot theme (toolbar, status bar, accent color etc.) does not reflect colors of ConnectBot logo
Hello,

currently the ConnectBot theme does not reflect the colors of the ConnectBot logo:

Image

But I think it should.

Could you please make the ConnectBot theme (toolbar, status bar, accent color etc.) make reflect the colors of the ConnectBot logo, as described in the Google Material Design guidelines over there:

https://www.google.com/design/spec/style/color.html#color-ui-color-application

?

Regards

### PR DESCRIPTION
**Pull request by kruton**
Fixes #167

### CODE REVIEW

**Comment by kruton** [comment]
material-cb

**Comment by kruton** [comment]
@jklein24 @bengolds I'm going to submit this, but I'm open to color palette changes or whatever.

**Comment by jklein24** [comment]
@bengolds, should we get some UX input on this?

**Comment by bengolds** [comment]
I don't think we need to. We're free to pick colors that make us happy :)

**Pull request merged**
