### PR TITLE
Add downloadable fonts  (Google flav. only- OSS falls back to current system "monospace", fixes #458)

### LINKED ISSUE #458: Changing fonts
It would be great if one could change the font of connectbot. 

Personally I use the font [Hack](https://github.com/chrissimpkins/Hack) because it's a great monospaced font. What makes this a necessity though is that I'm a heavy user of Vim/Neovim and that plugins like air-/powerline demand a few special glyphs to be patched into the font. [Hack](https://github.com/chrissimpkins/Hack) for example already has those glyphs patched which are essential for proper rendering of some advanced features.

### PR DESCRIPTION
**Pull request by fat-tire**
This actually adds some [functionality](https://developer.android.com/guide/topics/ui/look-and-feel/downloadable-fonts), so please check the crap out of it.  I tried to make it as compatible with #565 as I could, so that if you wanted to ALSO bundle in your own fonts beyond these downloadable ones, the code from @DAlexIV will hopefully slip right in.

Also, this was definitely working before the slew of changes added in #608 was merged.  I built it again post-those changes and it still seemed to work, but wasn't tested as thoroughly.  

Also-- some of the monospaced fonts (VT323 and Space Mono) kern a few letter combos like "ff" or "fi" which narrow the space used and it's not quite monospace any more and that screws up Connectbot's backspacing.  I looked briefly for ways to ignore kerning hints (there's a deprecated attribute/method) in that Paint object and it still looks possible, but I didn't explore too much.  For now those two fonts are commented out.

Anyway seems to work okay.  Please try it!

Here are those chromebook images again. Works great in Chrome OS.  If I think of anything else to add i'll do so.

Again, thanks to @DAlexIV who got this started before the move to minsdk 14 made the downloadable part possible.

ft

### CODE REVIEW

**Comment by kruton** [comment]
While you're using the Chromebook, could you fix the double back arrow
thing? I forgot what the flag was they presented at Google I/O, but it was
something simple.

Embarassingly I don't have a new enough Chromebook to develop on.

>

**Comment by fat-tire** [comment]
Sure...I think you're talking about [this](https://www.youtube.com/watch?v=6kIZ_u4QE9U&t=13m12s), no?
```
<meta-data android:name=
     "WindowManagerPreference:SuppressWindowControlNavigationButton"
     android:value="false" />
```
Do you want this backspace protection on all activities?  Override `onBackButtonPressed()` everywhere too?

ft

**Comment by kruton** [comment]
I'm not sure where `onBackButtonPressed` is called from (from `onKey` somehow), so we might already intercept it where it makes sense.

**Comment by fat-tire** [comment]
I'll take a look-- I don't think the current Samsung Pro (my CB) is honoring the manifest flag yet though so it makes it kind of hard to test/confirm it's working.  Let me play with it a bit.

Also, I was thinking-- having multiple windows to permit more than one connection at a time might be cool.  That's just a thought-- i haven't tried it yet.  Off the top of your head, do you see any situation in which having more than one active session active in a window simultaneoulsy might confuse things?

**Comment by fat-tire** [comment]
Just following up-- did a ChromeOS update yesterday and the double-back arrows persist even on Google apps like the Play Store..  When the manifest settings are recognized by my CB and I can confirm everything works, I'll submit the changes as a separate PR.

**Comment by fat-tire** [comment]
Hey @Kruton-- quick question-- this commit, #612, #611, #610, #609 etc have been sitting around for 7 months now and are going out of date.  I'm also looking forward to #627, #615, and others.  Is there anything further that needs to be done to get you to accept these commits?  I thought maybe the project was dead, but I see there is ongoing development in the last few weeks.

I'd like to keep the Connectbot up to date on my chromebook with upstream changes, but w/the font and other support that I see languishing in the PR section.

Please advise & happy holidays.

**Comment by kruton** [comment]
Sorry @fat-tire I'm rewriting everything involving the UI and I'm a bit behind schedule. I'll take a look at all these PRs and get them working with the new UI rewrite.

**Comment by fat-tire** [comment]
@kruton -- Gotcha.  That's exciting to hear.  Looking forward to the new UI and the updates!

Happy holidays (again)

**Comment by fat-tire** [comment]
Hey quick update-- since this was written almost a year ago, [androidX/Jetpack](https://developer.android.com/jetpack/androidx) was introduced by Google, so you'll probably want to replace:

```
import android.support.v4.provider.FontRequest;
import android.support.v4.provider.FontsContractCompat;
```

with

```
import androidx.core.provider.FontRequest;
import androidx.core.provider.FontsContractCompat;
```

And of course add the above to `build.gradle`.

Cheers.

**Comment by oblitum** [comment]
Hey folks, could someone share what happened here, the PR was great forever with merge on hold, then it suddenly just died without any explanation? I really wished this for support of nerd fonts.

**Comment by oblitum** [comment]
Nevermind... just moved to Termux.

**Comment by fat-tire** [comment]
Dunno what happened besides four+ years passing.  :man_shrugging:

**Comment by oblitum** [comment]
@fat-tire, okay no problem, Termux is just much better and I was missing on it, so it was in the end good for me to have this missing which forced into alternatives. Sad your work seem to have been wasted.

**Comment by guysoft** [comment]
Do you use something to store ssh presets on termux?

**Comment by fat-tire** [comment]
@guysoft [look](https://www.ssh.com/academy/ssh/config) at `~/.ssh/config`

**Pull request closed without merging**
