### PR TITLE
Add new icons to add/edit host view.

### PR DESCRIPTION
**Pull request by khorimoto**

### CODE REVIEW

**Comment by kruton** [comment]
Sorry, the latest merge from @alescdb broke your keyboard reference.

**Comment by khorimoto** [comment]
Fixed. Thanks for catching it.

**Comment by jklein24** [comment]
Should we be using svgs like @alescdb described in https://github.com/connectbot/connectbot/pull/321

**Comment by khorimoto** [comment]
Switched to SVGs.

**Pull request merged**
