### PR TITLE
Change 'add box' and 'folder open' icons to white versions

### LINKED ISSUE #322: Public keys activity is using dark icons instead of light
screenshot_20151022-110044-01

### PR DESCRIPTION
**Pull request by johnheroy**
Improves contrast in public keys toolbar. Fixes #322.

pubkey toolbar icons

### CODE REVIEW

**Comment by jklein24** [comment]
Maybe we should use svgs like in https://github.com/connectbot/connectbot/pull/321

**Comment by johnheroy** [comment]
Done, just pushed a commit to use vectors instead of pngs.

**Comment by jklein24** [comment]
Linter...

**Comment by alescdb** [comment]
@johnheroy Did you use context menu New -> Vector drawable to import your xml ? Because it seems you have unsupported tag in your xml (Group).

Here is the folder icon imported with Android Studio context menu :
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24.0"
        android:viewportHeight="24.0">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M20,6h-8l-2,-2H4c-1.1,0 -1.99,0.9 -1.99,2L2,18c0,1.1 0.9,2 2,2h16c1.1,0 2,-0.9 2,-2V8c0,-1.1 -0.9,-2 -2,-2zm0,12H4V8h16v10z"/>
</vector>
```

**Comment by johnheroy** [comment]
I didn't import the svg with Android Studio so I'll give that a shot
instead for the add box too

**Pull request merged**
