### PR TITLE
Replace unicode keys by vector drawable

### PR DESCRIPTION
**Pull request by alescdb**
Note that this need Android Studio 1.4 and gradle android plugin 1.4 (for backward compatibility)
This resolves issue #161

screenshot_20151022-101216

### CODE REVIEW

**Comment by rhansby** [comment]
Sorry if this is a dumb question, but why did you choose to represent icons as SVGs in XML instead of converting them to PNGs?

**Comment by alescdb** [comment]
Vector drawable are supported natively since lollipop (>=21), so you don't have to care about resolution and/or pixelisation. Since Android Studio 1.4/gradle 1.4 we get backward compatibility, so gradle creates the PNGs for all dpi for you automatically at build time.
So instead of having 5 PNGs (mdpi, hdpi, ...) to work with, you only have 1 xml file (also if you build a project for >= 21, your APK will be significantly smaller).
Other advantage, all Material Design icons (from https://www.google.com/design/icons/) are avalable for import directly in Android Studio (right clik menu New -> Vector Drawable). 
In my opinion, we should now use only vector drawable.
Of course this is only my opinion :-)

**Comment by jklein24** [comment]
Cool! Happy to merge as soon as the linter is happy.

**Comment by alescdb** [comment]
Lint is happy with me :-)

From what I see in travis-ci logs, lint warnings are old ones.
I think there is something wrong with the check-lint script (or it's cache)

**Comment by rhansby** [comment]
Thanks for the explanation @alescdb!

**Comment by alescdb** [comment]
@jklein24 I've checked and rechecked, lint warnings are not related to the files I've modified.
Aren't lint checks gradle plugin dependent ?

**Comment by kruton** [comment]
Yes, it will have new lint checks.  But the "string/button_key_tab" lint error is caused by this change. I can switch to newer gradle in a different change.

**Comment by alescdb** [comment]
Thanks @kruton and sorry about the missed button_key_tab, but when I remove it, do I need to removed it in all translations ? If I don't I get a lint error.

**Comment by alescdb** [comment]
@kruton This time I'm 100% sure none of the warnings are mine :-)
Now the question is how to update or delete `$HOME/.cache/lint/lint-results.xml` on tavis-ci ?

**Comment by kruton** [comment]
I didn't clear out the PR.321 cache before restarting the build. I've  just done that.

**Pull request merged**
