### PR TITLE
Add button for fdroid + change the one for google play

### PR DESCRIPTION
**Pull request by Poussinou**

### CODE REVIEW

**Comment by kruton** [comment]
Unfortunately I do not control what f-droid ships, so I'm uncomfortable adding a link here.

**Comment by Poussinou** [comment]
They simply build your app from sources, controlling there's no proprietary binaries or dependencies, you can maybe talk with them, but if you don't want this button I can close the PR

**Comment by kruton** [comment]
How about no button, but text that it's also available on F-Droid with the caveat that it is not built by the ConnectBot team?

**Comment by Poussinou** [comment]
As you want, I'll modify this tomorrow

**Comment by Poussinou** [comment]
Is this ok now?

**Comment by KamranMackey** [comment]
@Poussinou Looks good, but it could use a few typo fixes. `build` should be `built`, the a in Android should be capitalized, and the colon next to "find it here" should not have a space next to it.

Just my two cents.

**Comment by Poussinou** [comment]
Sorry about that

**Pull request closed without merging**
